### ISSUE TITLE
MyDiscord message broke!

### ISSUE THREAD

**Issue by Gxorge** [justinoboyle/mydiscord#11]
I have just tried to launch discord this morning, but when it loads the window goes dark and I can't click the text that appears so I can't use discord. Please, could you help me resolve this issue. This issue seems to be happening for both regular Discord and Canary.
![discordcanary_2017-06-26_07-39-28](https://user-images.githubusercontent.com/24527481/27527244-a03780ae-5a42-11e7-9880-9c38bc2cc041.png)

**Comment by staticsn0w** [comment]
yep! its completely broken and its pissing me off :(

**Comment by utf-4096** [comment]
same here

**Comment by justinoboyle** [comment]
ok, noted. discord changed some styling. will fix in a few... apologizes for this!

**Comment by justinoboyle** [comment]
ok you should be good now. removed the modal. sorry about that

**Comment by Gxorge** [comment]
Thanks!

**Comment by justinoboyle** [comment]
rolled out new notification system
